### ISSUE TITLE
Windows: add path to FPC to PAHT env variable

### ISSUE THREAD

**Issue by galfar** [gcarreno/setup-lazarus#15]
Hi,
any chance after Lazarus installation is finished the path to fpc.exe could be added to PATH environmental variable? It looks like the FPC version could be taken from Laz installer name `lazarus-2.2.0-fpc-3.2.2-win64.exe`.  
It's possible to use directly e.g. `D:\a\_temp\lazarus\fpc\3.2.2\bin\x86_64-win64\fpc.exe` now
but that looks pretty fragile.

Or is there some way how to get path to FPC (or at least FPC version) from lazbuild that I missed?

**Comment by gcarreno** [comment]
Hey Marek(@galfar),
CC: Benito (@benibela)

First of all, please let me apologise for taking so long to answer this.

Hummm, interesting :thinking:, I was under the impression that the installer would add an entry for both the IDE(`lazbuild.exe`, `lazarus.exe`) and the compiler(`fpc.exe`) to the system PATH variable.

To be honest I'm not a Windows person any more. I've been Linux only for many years now and I don't have a Windows machine to test this on. But since the Debian packages add the binaries to `/usr/bin`, this is not an issue under Linux.

From the way we invoke `lazbuild` in the build scripts, at least the path for `lazbuild` and `lazarus` are rightly setup under Windows. I'm quite baffled that the installer itself does **NOT** add the path to where the `fpc.exe` is.

Since I only use Lazarus when doing all my code: CLI and GUI, I'm always relying on an available `lazbuild` to compile my code. And I relegate all the immense command line params to be sorted out by `lazbuild` specified by `progname.lpi`.

If any of you can give me a compelling reason to support using:
```console
> fpc source1.pas source2.pas -o progname.exe
```
Instead of:
```console
> lazbuild progname.lpi
```
Then I'll try and find out how to add the correct path to the system PATH variable.

But in the end, what we need is to make sure that the `lazarus-<version>-fpc-<version>-win64.exe` installer really sets the PATH for both the compiler and the IDE.
I could implement it as a quick fix, but ultimately, this is the responsibility of the installer. At least in my opinion.

And please allow me one very dumb question: Are you sure that the installer does not add an entry to where `fpc.exe` is installed?

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Marek(@galfar),
CC: Benito (@benibela)

In the mean time I've asked the question about setting the PATH to `fpc.exe` on the forum:
- [Does the windows installer provided on SF set a PATH to fpc.exe?](https://forum.lazarus.freepascal.org/index.php/topic,59510.0.html)

So, please feel free to also monitor that.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Marek(@galfar),
CC: Benito (@benibela)

**I HATE BEING OLD!!!**

After a bit of back and forth on the forum thread, we have come to the conclusion that I'm the one adding the location of `lazbuild` to the system :disappointed: 

So this means I now have to do it for the location of FPC, of course :smile: 

This will come when I release 3.1.0 with cache support. I've made the mistake to **NOT** start the cache upgrade on it's own branch to then merge it to `main`, and now I've made several commits that I think will break the whole thing if I release it before I finish the cache upgrade. Yes, silly me for being a solo on this repo and breaking the golden rules of git workflows :face_exhaling: 

Cheers,
Gus

**Comment by galfar** [comment]
Thanks for implementing this in `setup-lazarus`, it works well now.

My use case is for a library that needs to work without Lazarus as well so I have 
some build scripts for demos etc. also for FPC directly. And since     
`setup-lazarus` is a convenient way to install both Lazarus and FPC 
I wanted to also run FPC-only build scripts for testing with GH Actions. 

Another time I needed to use FPC directly was because there's no way to pass 
custom compiler flags to `lazbuild`. Yes, you can tell it which build mode to use
but Lazarus build modes in `lpi` files cannot inherit from "base" mode (like in Delphi). 
And keeping say 10 build modes in sync (search paths, ...) just to have one compiler option or flag different is not very appealing.
