### ISSUE TITLE
Added Lazarus 2.0.1.0 + FPC 3.2.0

### ISSUE THREAD

**Issue by salvadorbs** [gcarreno/setup-lazarus#5]
As title.

**Comment by gcarreno** [comment]
Hey @salvadorbs ,

Have a look at the comment I left on the PR.

Many thanks!!

Cheers,
Gus

**Comment by gcarreno** [comment]
Closing due to lack of response either here or on PR.

**Comment by salvadorbs** [comment]
Sorry for delay, but in the end, I preferred to abandon your action, in favor of FPCUpDeluxe (it is slow, but I can easily insert patch for Laz or FPC) and git submodules for 3p comps (OPM doesn't allow install old version of a package)

**Comment by gcarreno** [comment]
Hey @salvadorbs ,

I'm curious on how you're using `fpcupdeluxe` via command line.

In my humble experience, I've been using it as a GUI app and was not aware you can use it command line only!

Cheers,
Gus

**Comment by salvadorbs** [comment]
Ops... I mean FPCUp (command line, https://github.com/LongDirtyAnimAlf/Reiniero-fpcup) and not FPCUpDeluxe (GUI). If you want see my workflow file, you can find here https://github.com/salvadorbs/Asuite/blob/develop/.github/workflows/main.yml.

**Comment by gcarreno** [comment]
Hey @salvadorbs ,

Uff, thanks for that. I actually thought about that when I was reading your message but, since I'm always doubting my own knowledge, due to the fact that I've been out of programming for so long, I kinda believed you knew best.

Thanks for your workflow link, I'm very interested in what you have to show me and will look at it right away!!

Grazie mille!!

Cheers,
Gus
